coverage:
  status:
    project:
      default:
        target: 100
        threshold: 20
        paths: "lib/"
    patch:
      default:
        target: 100
        threshold: 20
        paths: "lib/"
