coverage:
  status:
    project:
      default:
        target: 100
        threshold: 15
        paths: 'lib/'
    patch:
      default:
        target: 100
        threshold: 15
        paths: 'lib/'
