name: ckb_sdk_dart
version: 0.21.0
authors:
  - duanyytop <duanyytop@gmail.com>
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: duanyytop <duanyytop@gmail.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  dio: ^2.0.15
  pointycastle: ^1.0.1
  bip_bech32: ^0.1.3
  test_coverage: ^0.3.0
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
