name: ckb_sdk_dart
version: 0.26.2
homepage: https://github.com/duanyytop/ckb_sdk_dart
description:  A Dart SDK for Nervos CKB which is a public/permissionless blockchain, the layer 1 of Nervos network. 

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  dio: ^3.0.8
  pointycastle: ^1.0.2
  bip_bech32: ^0.1.3
  test_coverage: ^0.4.0
  http: ^0.12.0+4
  hex: ^0.1.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
