name: ckb_sdk_dart
version: 0.22.1
homepage: https://nervos.org
authors:
  - duanyytop <duanyytop@gmail.com>
description:  A Dart SDK for Nervos CKB which is a public/permissionless blockchain, the layer 1 of Nervos network. The SDK supports rpc, address, signature, serialiaztion modules.

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  dio: ^2.1.0
  pointycastle: ^1.0.1
  bip_bech32: ^0.1.3
  test_coverage: ^0.3.0
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
