version: 2.1
jobs:
  build:
    docker:
      - image: google/dart

    steps:
      - checkout

      - run:
          name: Install dependeces
          command: pub get

      - run:
          name: Run the SDK tests
          command: pub run test
