name: ckb_cli
version: 0.1.0
authors:
  - duanyytop <duanyytop@gmail.com>
description: A command-line application for ckb sdk dart.

executables:
  ckb_cli:

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: '^1.5.1'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
